### DISCUSSION TITLE
commitsar github action fails with "push" as action trigger?

### DISCUSSION THREAD

**Discussion by amolvyavahare10** [aevea/commitsar#388] [Q&A]
Recently I was trying to use it with my repo and the action was failing when i tried to use aevea/commitsar

*worked fine with "pull_request"

here is what i've added in the yml: 

```
name: Commit Check

on: push

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Commit Check
      # uses: aevea/commitsar@v0.16.0
      uses: docker://aevea/commitsar 
```
