### ISSUE TITLE
Commitsar fails with 0 commits  to check on main branch 

### ISSUE THREAD

**Issue by kowalczykp** [aevea/commitsar#354]
When dealing with commits on branches/PRs, commitsar works as expected, but it behaves inconsistently on main branch:

When PR lands on main, as the last commit (fast-forward merge without merge commit) and CI (gitlab CI) manages to finish the commitsar pipeline before any new changes land, everything works as expected: Only a single/last commit is being checked.

When new changes land on main BEFORE the commitsar pipeline runs for previous commits, the following error happens:
```
$ commitsar --verbose
[DEBUG] Starting pipeline: commit-pipeline
Starting analysis of commits on branch HEAD
[DEBUG] Stopped getting commits on branch: object not found
[DEBUG] Stopped getting commits on branch: object not found
0 commits filtered out
Found 0 commit to check
[DEBUG] All pipelines complete
[DEBUG] [commit-pipeline] No commits found, please check you are on a branch outside of main
Some errors were found
```

While this mostly happens for frequent commits scenarios, the easiest way to deterministically reproduce it is to re-run a pipeline that previously passed on the main branch, but now has new commits ahead of it. This is always consistent and results in failure.

Possibly related: https://github.com/aevea/commitsar/issues/167

**Comment by kowalczykp** [comment]
The current workaround for us is, to use two separate pipelines, where the main branch validation operates on the commit range. Gitlab CI based workaround relying on CI populated variables that help to identify the last commit:

```
validate-commits-branches:
  stage: test
  image: aevea/commitsar
  except:
    refs:
      - master
  script:
    - git fetch origin master
    - commitsar --verbose
  needs: []

validate-commits-master:
  stage: test
  image: aevea/commitsar
  only:
    refs:
      - master
  script:
    - commitsar --verbose $CI_COMMIT_BEFORE_SHA:$CI_COMMIT_SHA
  needs: []

```
