### ISSUE TITLE
commitsar not working on main branch as ref

### ISSUE THREAD

**Issue by israelshenkar** [aevea/commitsar#499]
Starting analysis of commits on branch
reference not found

when added master branch to my new repo it started working again

**Comment by fallion** [comment]
Hi @israelshenkar 

Which version are you using? Just so I can debug from there.

**Comment by t3hmrman** [comment]
Hey for anyone that runs into this, it was a case of [RTFM](https://en.wikipedia.org/wiki/RTFM). Copy pastable workflow:

```yaml
name: Lint

on:
  pull_request:

jobs:
  ensure-conventional-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Ensure conventional commits
        uses: aevea/commitsar@916c7b483225a30d3a17f407fa25f5b25888ea69 # v0.20.2
```
